apiVersion: v1
kind: Service
metadata:
  name: auth-server-service
  namespace: todo-app
  labels:
    app: auth-server
    app.kubernetes.io/name: auth-server
spec:
  type: NodePort
  selector:
    app: auth-server
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30801  # External access via Minikube IP:30801
    protocol: TCP
    name: http
