apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/instance: todo-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
