apiVersion: v2
name: todo-app
description: A Helm chart for the Evolution of Todo full-stack application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - todo
  - nextjs
  - fastapi
  - kubernetes
  - full-stack
maintainers:
  - name: Todo App Team
home: https://github.com/Demolinator/Talal-s-TDA
sources:
  - https://github.com/Demolinator/Talal-s-TDA
