apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-app.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.backend.type }}
  selector:
    app: backend
  ports:
  - port: {{ .Values.services.backend.port }}
    targetPort: {{ .Values.services.backend.port }}
    {{- if eq .Values.services.backend.type "NodePort" }}
    nodePort: {{ .Values.services.backend.nodePort }}
    {{- end }}
    protocol: TCP
    name: http
