apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-app.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.frontend.type }}
  selector:
    app: frontend
  ports:
  - port: {{ .Values.services.frontend.port }}
    targetPort: {{ .Values.services.frontend.port }}
    {{- if eq .Values.services.frontend.type "NodePort" }}
    nodePort: {{ .Values.services.frontend.nodePort }}
    {{- end }}
    protocol: TCP
    name: http
