{{- if .Values.envFromConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
